version: '3.3'

services:

   stream:
      
      image: ivanduque0/mjpg-streamer-raspberry:v1

      ports:
         - 8080:8080
      devices:
         - /dev/vchiq
         
      command: ["input_raspicam.so -x 360 -y 240 -fps 20"]
      #command: ["input_raspicam.so -x 640 -y 480 -fps 20"]
         
      privileged: true
      
      restart: always

   pines:
      image: ivanduque0/pin-control-raspberry:v1

      devices:
         - /dev/gpiomem

      volumes:
         - .:/app
      
      env_file:
         - .env.pines
      
      restart: always
      
      #depends_on:
         #- stream
